"""
Phase 3: SAM2 Segmentor — Instance Segmentation for Food Plates

Replaces the crude elliptical/circular mask overlays with precise,
pixel-perfect boundaries generated by Segment Anything 2 (SAM 2).

Model: facebook/sam2-hiera-tiny (Hiera-Tiny backbone)
VRAM:  ~500 MB
Speed: ~0.4s per image on RTX 3050

Pipeline Role:
  Grounding DINO (Bboxes) → [SAM 2 (Masks)] → Depth Anything (Volume)
"""

from __future__ import annotations

import cv2
import numpy as np
from PIL import Image
from typing import Optional

from app.services.model_registry import get_sam2, DEVICE

# ─── Mask configuration ───────────────────────────────────────────────────────
MASK_THRESHOLD = 0.0   # Logit threshold for binary mask conversion


def segment_food_items(
    image_path: str,
    bboxes_px: list[list[int]]
) -> tuple[Optional[np.ndarray], list[np.ndarray]]:
    """
    Generate pixel-perfect segmentation masks for all detected bounding boxes
    using the Segment Anything 2 (SAM 2) model.

    Args:
        image_path: Path to the uploaded meal image.
        bboxes_px:  List of bounding boxes in pixel coordinates [[x1, y1, x2, y2], ...]

    Returns:
        (combined_mask, individual_masks) where:
          combined_mask: (H, W) uint8 array containing instance IDs (0=bg, 1=first item, 2=second, ...)
          individual_masks: List of (H, W) binary bool arrays (one per input bbox)
        Returns (None, []) if SAM 2 is unavailable or inputs are empty.
    """
    sam2_bundle = get_sam2()
    if sam2_bundle is None or not bboxes_px:
        return None, []

    try:
        import torch
        model     = sam2_bundle["model"]
        processor = sam2_bundle["processor"]

        # Load image
        pil_image = Image.open(image_path).convert("RGB")
        img_w, img_h = pil_image.size

        # Format input boxes for processor: list of list of boxes (batch size 1)
        # Bbox shape expected: [batch_size, num_boxes, 4]
        input_boxes = [[box for box in bboxes_px]]

        # Prepare inputs
        inputs = processor(
            images=pil_image,
            input_boxes=input_boxes,
            return_tensors="pt"
        ).to(DEVICE)

        # Run inference
        with torch.no_grad():
            outputs = model(**inputs)

        # Post-process masks back to original image size
        # res_masks is a list of tensors of shape (num_masks, 3, H, W)
        res_masks = processor.post_process_masks(
            outputs.masks,
            inputs.original_sizes,
            inputs.reshaped_input_sizes
        )

        individual_masks = []
        combined_mask = np.zeros((img_h, img_w), dtype=np.uint8)

        if res_masks and len(res_masks) > 0:
            # We batched 1 image, so take the first index
            # shape: (num_boxes, 3, H, W)
            # The model outputs 3 candidates per box; we select the first one (highest confidence score)
            masks_tensor = res_masks[0]  # shape: (num_boxes, 3, H, W)
            
            for idx, box_masks in enumerate(masks_tensor):
                # Take candidate 0 (shape: H, W)
                mask_bool_tensor = box_masks[0]
                mask_np = mask_bool_tensor.cpu().numpy()  # boolean array (H, W)
                individual_masks.append(mask_np)

                # Add to combined instance mask (1-indexed for instances)
                instance_id = idx + 1
                combined_mask[mask_np] = instance_id

        print(f"[Segmentor] SAM 2 generated {len(individual_masks)} masks")
        return combined_mask, individual_masks

    except Exception as e:
        print(f"[Segmentor] SAM 2 segmentation failed: {e}")
        return None, []


def overlay_mask_on_image(
    image_bgr: np.ndarray,
    mask: np.ndarray,
    color: tuple[int, int, int],
    alpha: float = 0.4
) -> np.ndarray:
    """
    Overlays a colored binary mask on a BGR image.

    Args:
        image_bgr: Original BGR image.
        mask:      Binary mask (H, W) boolean/uint8.
        color:     BGR color tuple.
        alpha:     Transparency factor.

    Returns:
        Image with mask overlay.
    """
    overlay = image_bgr.copy()
    overlay[mask > 0] = color
    return cv2.addWeighted(overlay, alpha, image_bgr, 1 - alpha, 0)
